set nocompatible
filetype off

"" Package managment
source ~/.vim/bundles
"" Package specific settings
for f in split(glob('~/.vim/settings.d/*'), '\n')
        exe 'source' f
endfor
"" Global Keymaps
source ~/.vim/keymaps
"" Global Aliases
source ~/.vim/aliases

"" ## Common options
set noswapfile nobackup nowritebackup
set relativenumber
set incsearch smartcase

"" Wildmenu
set wildmenu
set wildmode=list:longest,full

set wildignore+=*.sw?                            " Vim swap files
set wildignore+=*.bak,*.?~,*.??~,*.???~,*.~      " Backup files
set wildignore+=*.luac                           " Lua byte code
set wildignore+=*.jar                            " java archives
set wildignore+=*.pyc                            " Python byte code
set wildignore+=*.stats                          " Pylint stats

"" Prefare spaces over tabs
set tabstop=4 softtabstop=4 shiftwidth=4
set shiftround expandtab

"" Colors
set t_Co=256
colorscheme tomorrownight

"" Allow hidden buffers
set hidden

"" Annoy me
match Error /\s\+$/

set laststatus=2

autocmd FileType python setlocal et ts=4 sw=4
autocmd FileType coffee setlocal et ts=2 sw=2

" Autoresize splits
au VimResized * exe "normal! \<c-w>="

" folding method
set foldmethod=marker

