local function fresh_vault()
  local tmp = vim.fn.tempname()
  vim.fn.mkdir(tmp, "p")
  _G.KB_VAULT_OVERRIDE = tmp
  package.loaded["kb.config"] = nil
  package.loaded["kb.at"] = nil
  return tmp
end

describe("kb.at.parse", function()
  it("parses bucketed mention like @reports/vanya", function()
    fresh_vault()
    local at = require("kb.at")
    local m = at.parse("hi @reports/vanya there", 4)
    assert.are.same({ bucket = "reports", name = "vanya", raw = "@reports/vanya" }, m)
  end)

  it("parses bare @vanya as bucketless", function()
    fresh_vault()
    local at = require("kb.at")
    local m = at.parse("hi @vanya there", 4)
    assert.are.same({ bucket = nil, name = "vanya", raw = "@vanya" }, m)
  end)

  it("returns nil if cursor is not on a mention", function()
    fresh_vault()
    local at = require("kb.at")
    assert.is_nil(at.parse("no mention here", 1))
  end)

  it("parses mention regardless of cursor position within the mention span", function()
    fresh_vault()
    local at = require("kb.at")
    local m = at.parse("hi @projects/payments now", 10)
    assert.are.same({ bucket = "projects", name = "payments", raw = "@projects/payments" }, m)
  end)
end)

describe("kb.at.resolve", function()
  it("resolves a flat-form entity file", function()
    local vault = fresh_vault()
    vim.fn.mkdir(vault .. "/projects", "p")
    vim.fn.writefile({ "# Payments" }, vault .. "/projects/payments.md")
    local at = require("kb.at")
    local p = at.resolve({ bucket = "projects", name = "payments" })
    assert.are.equal(vault .. "/projects/payments.md", p)
  end)

  it("resolves a folder-form entity via index.md", function()
    local vault = fresh_vault()
    vim.fn.mkdir(vault .. "/domains/labeling", "p")
    vim.fn.writefile({ "# Labeling" }, vault .. "/domains/labeling/index.md")
    local at = require("kb.at")
    local p = at.resolve({ bucket = "domains", name = "labeling" })
    assert.are.equal(vault .. "/domains/labeling/index.md", p)
  end)

  it("prefers flat form when both exist", function()
    local vault = fresh_vault()
    vim.fn.mkdir(vault .. "/domains/labeling", "p")
    vim.fn.writefile({ "FLAT" }, vault .. "/domains/labeling.md")
    vim.fn.writefile({ "FOLDER" }, vault .. "/domains/labeling/index.md")
    local at = require("kb.at")
    local p = at.resolve({ bucket = "domains", name = "labeling" })
    assert.are.equal(vault .. "/domains/labeling.md", p)
  end)

  it("returns nil if neither flat nor folder form exists", function()
    fresh_vault()
    local at = require("kb.at")
    assert.is_nil(at.resolve({ bucket = "projects", name = "missing" }))
  end)

  it("maps people sub-buckets to people/<bucket>/<name>.md", function()
    local vault = fresh_vault()
    vim.fn.mkdir(vault .. "/people/reports", "p")
    vim.fn.writefile({ "# Vanya" }, vault .. "/people/reports/vanya.md")
    local at = require("kb.at")
    local p = at.resolve({ bucket = "reports", name = "vanya" })
    assert.are.equal(vault .. "/people/reports/vanya.md", p)
  end)
end)
