export ZSH=$HOME/.zsh/ohmyzsh
ZSH_THEME="agnoster"

ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(brew)

# User configuration
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

export TERM='xterm-256color'
export EDITOR=$(which vim)

WORKON_HOME=~/.venvs
source /usr/local/bin/virtualenvwrapper.sh

alias l='ls -a'
