export ZSH=$HOME/.zsh
ZSH_THEME="agnoster"

ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(brew)

# User configuration
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
   export EDITOR='mvim'
fi

export TERM='xterm-256color'
export EDITOR=$(which vim)

WORKON_HOME=~/.venvs
source /usr/local/bin/virtualenvwrapper.sh
